spring:
  application:
    name: Config-Client
eureka:
  instance:
    ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

